import Connect from "@/components/Connect";
import React from "react";

export const metadata = {
  title: "Connect",
  description: "Generated by create next app",
};

const ConnectPage = () => {
  return <Connect />;
};

export default ConnectPage;
