import React from "react";
import OurCraft from "@/components/our_craft";

export const metadata = {
  title: "Our Craft",
  description: "Generated by create next app",
};

const OurCraftPage = () => {
  return <OurCraft />;
};

export default OurCraftPage;
