import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "bootstrap/dist/css/bootstrap.min.css";
import Script from "next/script";

const MEASUREMENT_ID = process.env.NEXT_PUBLIC_MEASUREMENT_ID;

export const metadata = {
  title: "Distinct Origins",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/images/logo.png" sizes="any" />
      <Script
        src={`https://www.googletagmanager.com/gtag/js?id='${MEASUREMENT_ID}'`}
        strategy="afterInteractive"
      />
      <Script
        id="google-analytics"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `
           window.dataLayer = window.dataLayer || [];
           function gtag(){dataLayer.push(arguments);}
           gtag('js', new Date());
           gtag('config', '${MEASUREMENT_ID}', {
            page_path: window.location.pathname,
           })`,
        }}
      />
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
