import Products from "@/components/products";
import React from "react";

export const metadata = {
  title: "Products",
  description: "Generated by create next app",
};

const ProductPage = () => {
  return <Products />;
};

export default ProductPage;
